# Generated by Django 5.1.1 on 2026-05-06 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "payment_system",
                    models.CharField(
                        choices=[
                            ("bkash", "Bkash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=200, unique=True)),
                ("amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="app.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateTimeField(auto_now_add=True)),
                ("time_limit_minutes", models.IntegerField(default=10)),
                ("total_questions", models.IntegerField()),
                ("correct_answers", models.IntegerField(default=0)),
                ("wrong_answers", models.IntegerField(default=0)),
                ("skipped_answers", models.IntegerField(default=0)),
                ("score_percentage", models.FloatField(default=0)),
                ("mcq_ids_order", models.JSONField(default=list)),
                ("user_answers", models.JSONField(default=list)),
                ("correct_status", models.JSONField(default=list)),
                ("selected_chapters", models.JSONField(default=list)),
                ("selected_sub_lessons", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_attempts",
                        to="app.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="courses/"),
                ),
                ("total_subjects", models.PositiveIntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("one_month_price", models.IntegerField(default=0)),
                ("six_month_price", models.IntegerField(default=0)),
                ("one_year_price", models.IntegerField(default=0)),
                (
                    "subjects",
                    models.ManyToManyField(related_name="courses", to="app.subject"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="app.subject",
            ),
        ),
        migrations.CreateModel(
            name="SubLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mcq_count", models.IntegerField(db_index=True, default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_lessons",
                        to="app.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("option_1", models.CharField(max_length=255)),
                ("option_2", models.CharField(max_length=255)),
                ("option_3", models.CharField(max_length=255)),
                ("option_4", models.CharField(max_length=255)),
                ("previous_year", models.TextField(blank=True, null=True)),
                ("correct_answer", models.IntegerField(help_text="Use 1, 2, 3, or 4")),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcqs",
                        to="app.chapter",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcqs",
                        to="app.lesson",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcqs",
                        to="app.subject",
                    ),
                ),
                (
                    "sub_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcqs",
                        to="app.sublesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMasterProgress",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="master_progress",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("progress_data", models.JSONField(default=dict)),
                ("total_sub_lessons", models.IntegerField(default=0)),
                ("total_questions_answered", models.IntegerField(default=0)),
                ("total_correct_answers", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-last_updated"], name="app_usermas_last_up_193481_idx"
                    ),
                    models.Index(
                        fields=["user", "-last_updated"],
                        name="app_usermas_user_id_60fbd5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        default="defaults/default-avatar.png",
                        null=True,
                        upload_to="profile_pictures/",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_system",
                    models.CharField(
                        choices=[
                            ("bkash", "Bkash"),
                            ("nagad", "Nagad"),
                            ("rocket", "Rocket"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[(1, "1 Month"), (6, "6 Months"), (12, "12 Months")]
                    ),
                ),
                ("transaction_id", models.CharField(max_length=200)),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.transactionverification",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("transaction_id", "payment_system"),
                        name="unique_transaction_payment_system",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserCourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="app.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "course")},
            },
        ),
    ]
