# Generated by Django 5.1.1 on 2026-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcq",
            name="previous_year",
            field=models.TextField(blank=True, null=True),
        ),
    ]
