# Generated by Django 5.1.1 on 2026-04-27 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_mcq_previous_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateTimeField(auto_now_add=True)),
                ("time_limit_minutes", models.IntegerField(default=10)),
                ("total_questions", models.IntegerField()),
                ("correct_answers", models.IntegerField(default=0)),
                ("wrong_answers", models.IntegerField(default=0)),
                ("skipped_answers", models.IntegerField(default=0)),
                ("score_percentage", models.FloatField(default=0)),
                ("mcq_ids_order", models.JSONField(default=list)),
                ("user_answers", models.JSONField(default=list)),
                ("correct_status", models.JSONField(default=list)),
                ("selected_chapters", models.JSONField(default=list)),
                ("selected_sub_lessons", models.JSONField(default=list)),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_attempts",
                        to="app.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-exam_date"],
            },
        ),
    ]
