# Generated by Django 5.1.1 on 2026-04-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_course_usercourseenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="one_month_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="one_year_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="six_month_price",
            field=models.IntegerField(default=0),
        ),
    ]
