# Generated by Django 5.1.1 on 2026-04-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_transactionverification_payment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("transaction_id", "payment_system")},
        ),
    ]
