# Generated by Django 5.1.1 on 2026-04-28 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_payment_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("transaction_id", "payment_system"),
                name="unique_transaction_payment_system",
            ),
        ),
    ]
