# Generated by Django 5.1.1 on 2026-04-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_payment_unique_transaction_payment_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionverification",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
