# Generated by Django 5.1.1 on 2026-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_transactionverification_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="sublesson",
            name="mcq_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
