# Generated by Django 5.1.1 on 2026-05-01 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_sublesson_mcq_count"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMasterProgress",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="master_progress",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("progress_data", models.JSONField(default=dict)),
                ("total_sub_lessons", models.IntegerField(default=0)),
                ("total_questions_answered", models.IntegerField(default=0)),
                ("total_correct_answers", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-last_updated"], name="app_usermas_last_up_193481_idx"
                    ),
                    models.Index(
                        fields=["user", "-last_updated"],
                        name="app_usermas_user_id_60fbd5_idx",
                    ),
                ],
            },
        ),
    ]
